### ISSUE TITLE
Basic usage questions 

### ISSUE THREAD

**Issue by tvkit** [ronnygunawan/maui-redux#2]
I'm familiar with  both redux & vuex in the javascript environment, and I'm curious about your approach to using _maui-redux_ in a xamarin/maui app.  Do you persist into SecureStorage within a Reducer, or create a subscription and store therein?  Also, how do you expose the store?  A static member on the App seems like a reasonable location.

**Comment by ronnygunawan** [comment]
> Do you persist into SecureStorage within a Reducer, or create a subscription and store therein?

`PreferenceSubject` (and `PreferenceStore`) persists its value to `Microsoft.Maui.Essentials.Preferences`. Here's [link to the implementation](https://github.com/ronnygunawan/maui-redux/blob/23db44167969df508ffccf6dfac789083269fb32/src/RG.MAUI.Redux/PreferenceSubject.cs#L168-L204)

`Microsoft.Maui.Essentials.Preferences` implementation: https://github.com/dotnet/maui/tree/main/src/Essentials/src/Preferences

> Also, how do you expose the store? A static member on the App seems like a reasonable location.

You can either expose a static member or use a singleton dependency.
